---
- hosts: k3s_cluster
  gather_facts: yes
  become: yes
  roles:
    - { role: prereq }
    - { role: download }

- hosts: master
  gather_facts: yes
  become: yes
  roles:
    - { role: k3s/master }
    - { role: helm }

- hosts: node
  gather_facts: yes
  become: yes
  roles:
    - { role: k3s/node }
